[repository]
name = "volto-plate"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/kitconcept/volto-plate"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "kitconcept.plate"
path = "backend"
code_path = "src/kitconcept/plate"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "@kitconcept/volto-plate"
path = "frontend/packages/volto-plate"
code_path = "src"
changelog = "frontend/packages/volto-plate/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-plate/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "6bdd1efa3642c65710a3373c00637f50aca2b145"
generated_date = "2026-07-02 13:31:27"
