[repository]
name = "volto-plate"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/kitconcept/volto-plate"
compose = ["docker-compose.yml"]

# The steps to execute when running `uvx repoplone release`.
[repository.release]
steps = [
    "changelog",
    "version",
    "repository",
    "release_frontend",
    "frontend_artifact",
    "release_backend",
    "git",
    "gh_release",
    "bye",
]

# Register a new step to create the frontend artifact
[repository.release.registry.frontend_artifact]
title = "Create Frontend Artifact"
function = "local_step"
args = { entrypoint = "frontend._package:create_artifact" }

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "kitconcept.plate"
path = "backend"
code_path = "src/kitconcept/plate"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend.package]
name = "@kitconcept/volto-plate"
path = "frontend/packages/volto-plate"
code_path = "src"
changelog = "frontend/packages/volto-plate/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-plate/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "monorepo_addon"
template_version = "2c5463046f43a87e36d11a7edc2b4176b2d593aa"
generated_date = "2026-02-13 09:23:34"
