// Generated by `scripts/plate-i18n.mjs messages` from @plone/plate's
// catalogs. Do not edit: change Plate's `locales/en/common.json` instead.
// It only exists so Volto's i18n extraction picks up Plate's keys.
import { defineMessages } from 'react-intl';

export default defineMessages({});
