// Generated by `scripts/plate-i18n.mjs messages` from @plone/plate's
// catalogs. Do not edit: change Plate's `locales/en/common.json` instead.
// It only exists so Volto's i18n extraction picks up Plate's keys.
import { defineMessages } from 'react-intl';

export default defineMessages({
  'plate.slashMenu.groups.actions': {
    id: 'plate.slashMenu.groups.actions',
    defaultMessage: 'Actions',
  },
  'plate.slashMenu.groups.advancedBlocks': {
    id: 'plate.slashMenu.groups.advancedBlocks',
    defaultMessage: 'Advanced blocks',
  },
  'plate.slashMenu.groups.blocks': {
    id: 'plate.slashMenu.groups.blocks',
    defaultMessage: 'Blocks',
  },
  'plate.slashMenu.groups.textBlocks': {
    id: 'plate.slashMenu.groups.textBlocks',
    defaultMessage: 'Text blocks',
  },
  'plate.slashMenu.items.blockquote': {
    id: 'plate.slashMenu.items.blockquote',
    defaultMessage: 'Blockquote',
  },
  'plate.slashMenu.items.bulletedList': {
    id: 'plate.slashMenu.items.bulletedList',
    defaultMessage: 'Bulleted list',
  },
  'plate.slashMenu.items.callout': {
    id: 'plate.slashMenu.items.callout',
    defaultMessage: 'Callout',
  },
  'plate.slashMenu.items.calloutDescription': {
    id: 'plate.slashMenu.items.calloutDescription',
    defaultMessage: 'Insert a highlighted block.',
  },
  'plate.slashMenu.items.codeBlock': {
    id: 'plate.slashMenu.items.codeBlock',
    defaultMessage: 'Code Block',
  },
  'plate.slashMenu.items.heading2': {
    id: 'plate.slashMenu.items.heading2',
    defaultMessage: 'Heading 2',
  },
  'plate.slashMenu.items.heading3': {
    id: 'plate.slashMenu.items.heading3',
    defaultMessage: 'Heading 3',
  },
  'plate.slashMenu.items.heading4': {
    id: 'plate.slashMenu.items.heading4',
    defaultMessage: 'Heading 4',
  },
  'plate.slashMenu.items.heading5': {
    id: 'plate.slashMenu.items.heading5',
    defaultMessage: 'Heading 5',
  },
  'plate.slashMenu.items.heading6': {
    id: 'plate.slashMenu.items.heading6',
    defaultMessage: 'Heading 6',
  },
  'plate.slashMenu.items.numberedList': {
    id: 'plate.slashMenu.items.numberedList',
    defaultMessage: 'Numbered list',
  },
  'plate.slashMenu.items.table': {
    id: 'plate.slashMenu.items.table',
    defaultMessage: 'Table',
  },
  'plate.slashMenu.items.tableOfContents': {
    id: 'plate.slashMenu.items.tableOfContents',
    defaultMessage: 'Table of contents',
  },
  'plate.slashMenu.items.text': {
    id: 'plate.slashMenu.items.text',
    defaultMessage: 'Text',
  },
  'plate.slashMenu.items.threeColumns': {
    id: 'plate.slashMenu.items.threeColumns',
    defaultMessage: '3 columns',
  },
  'plate.slashMenu.items.title': {
    id: 'plate.slashMenu.items.title',
    defaultMessage: 'Title',
  },
  'plate.slashMenu.items.todoList': {
    id: 'plate.slashMenu.items.todoList',
    defaultMessage: 'To-do list',
  },
  'plate.slashMenu.noResults': {
    id: 'plate.slashMenu.noResults',
    defaultMessage: 'No results',
  },
});
