#!/usr/bin/env node
/**
 * Brings @plone/plate's translations (i18next JSON catalogs) into this
 * add-on's react-intl (gettext) catalogs, so Volto translates Plate's UI.
 *
 *   node scripts/plate-i18n.mjs messages
 *     Generates `src/plate/i18n/plateMessages.ts`, a `defineMessages` file
 *     with every Plate key, so Volto's i18n extraction adds them to
 *     `locales/volto.pot` and the `.po` files (and keeps them there).
 *
 *   node scripts/plate-i18n.mjs po
 *     Fills empty `plate.*` translations in `locales/<lang>/LC_MESSAGES/volto.po`
 *     from Plate's catalog for that language. Existing translations win.
 *
 * Both run as part of the add-on's `i18n` script.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const require = createRequire(import.meta.url);
const addonDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const plateLocalesDir = path.join(
  path.dirname(require.resolve('@plone/plate/package.json')),
  'locales',
);
const messagesFile = path.join(addonDir, 'src/plate/i18n/plateMessages.ts');
const addonLocalesDir = path.join(addonDir, 'locales');

/** `{ plate: { a: 'A' } }` -> `{ 'plate.a': 'A' }` (i18next `.` key separator). */
const flatten = (node, prefix = '', result = {}) => {
  for (const [key, value] of Object.entries(node)) {
    const id = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === 'object') {
      flatten(value, id, result);
    } else if (typeof value === 'string') {
      result[id] = value;
    }
  }
  return result;
};

/** i18next `{{name}}` -> ICU `{name}`. */
const toIcu = (text) => text.replace(/\{\{\s*(\w+)\s*\}\}/g, '{$1}');

const readPlateCatalog = (language) => {
  const file = path.join(plateLocalesDir, language, 'common.json');
  if (!fs.existsSync(file)) return undefined;
  return flatten(JSON.parse(fs.readFileSync(file, 'utf8')));
};

async function generateMessages() {
  const catalog = readPlateCatalog('en') ?? {};
  const entries = Object.keys(catalog)
    .sort()
    .map(
      (id) =>
        `  ${JSON.stringify(id)}: { id: ${JSON.stringify(id)}, defaultMessage: ${JSON.stringify(toIcu(catalog[id]))} },`,
    );

  const source = `// Generated by \`scripts/plate-i18n.mjs messages\` from @plone/plate's
// catalogs. Do not edit: change Plate's \`locales/en/common.json\` instead.
// It only exists so Volto's i18n extraction picks up Plate's keys.
import { defineMessages } from 'react-intl';

export default defineMessages({
${entries.join('\n')}
});
`;

  const options = (await prettier.resolveConfig(messagesFile)) ?? {};
  const formatted = await prettier.format(source, {
    ...options,
    filepath: messagesFile,
  });

  fs.mkdirSync(path.dirname(messagesFile), { recursive: true });
  fs.writeFileSync(messagesFile, formatted);
  console.log(
    `Generated ${path.relative(addonDir, messagesFile)} (${entries.length} messages)`,
  );
}

const unescapePo = (text) => text.replace(/\\"/g, '"').replace(/\\\\/g, '\\');
const escapePo = (text) => text.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

function fillPoFiles() {
  for (const language of fs.readdirSync(addonLocalesDir).sort()) {
    const poFile = path.join(
      addonLocalesDir,
      language,
      'LC_MESSAGES',
      'volto.po',
    );
    // English falls back to the default messages; nothing to fill.
    if (language === 'en' || !fs.existsSync(poFile)) continue;

    // Volto uses `pt_BR`, i18next usually `pt-BR`; also try the base language.
    const catalog = [
      language,
      language.replace('_', '-'),
      language.split('_')[0],
    ].reduce(
      (found, candidate) => found ?? readPlateCatalog(candidate),
      undefined,
    );
    if (!catalog) continue;

    let filled = 0;
    const po = fs
      .readFileSync(poFile, 'utf8')
      .replace(
        /^msgid "(plate\.(?:[^"\\]|\\.)*)"\nmsgstr ""$/gm,
        (match, msgid) => {
          const translation = catalog[unescapePo(msgid)];
          if (!translation) return match;
          filled += 1;
          return `msgid "${msgid}"\nmsgstr "${escapePo(toIcu(translation))}"`;
        },
      );

    fs.writeFileSync(poFile, po);
    console.log(`Filled ${filled} Plate translations in ${language}`);
  }
}

const command = process.argv[2];

if (command === 'messages') {
  await generateMessages();
} else if (command === 'po') {
  fillPoFiles();
} else {
  console.error('Usage: plate-i18n.mjs <messages|po>');
  process.exit(1);
}
